### ISSUE TITLE
Does not work on Mac

### ISSUE THREAD

**Issue by ashottonoyan** [OpenDevice/Arduino#2]
![screenshot 2015-03-13 04 32 17](https://cloud.githubusercontent.com/assets/612529/6652723/b88a4f7e-ca89-11e4-8e3d-8e952b02d45e.png)

**Comment by ricardojlrufino** [comment]
Please need to test because I do not have a Mac available

**Comment by ashottonoyan** [comment]
Can you update the DMG here? http://criativasoft.com.br/downloads/programas/arduino/

**Comment by ashottonoyan** [comment]
I think you have a typo here: plus-libparser-0.0.1.jar -> cplus-libparser-0.0.1.jar

**Comment by ashottonoyan** [comment]
Now getting this:
![screenshot 2015-03-15 15 52 23](https://cloud.githubusercontent.com/assets/612529/6655871/f43e6e1c-cb22-11e4-98af-cb7ba890987a.png)

**Comment by ricardojlrufino** [comment]
please, try now ! i have updated de download link

**Comment by ashottonoyan** [comment]
Download link contains the same version with the original error.

**Comment by ricardojlrufino** [comment]
the file just has the same name, you downloaded?

**Comment by ashottonoyan** [comment]
Yes. same error, doesn't work.

Cheers,
Ashot

**Comment by ricardojlrufino** [comment]
sorry, i will get a Mac to do some tests

**Comment by ashottonoyan** [comment]
Downloaded just now again. 

Still this in the Info.plist

$JAVAROOT/pde.jar:$JAVAROOT/arduino-core.jar:$JAVAROOT/antlr.jar:$JAVAROOT/apple.jar:$JAVAROOT/ecj.jar:$JAVAROOT/registry.jar:$JAVAROOT/quaqua.jar:$JAVAROOT/jssc-2.8.0.jar:$JAVAROOT/commons-codec-1.7.jar:$JAVAROOT/commons-exec-1.1.jar:$JAVAROOT/commons-httpclient-3.1.jar:$JAVAROOT/commons-logging-1.0.4.jar:$JAVAROOT/jmdns-3.4.1.jar:$JAVAROOT/jsch-0.1.50.jar:$JAVAROOT/jna.jar

**Comment by ricardojlrufino** [comment]
Add this and test:
rsyntax-autocomplete-2.6.0-SNAPSHOT.jar
rsyntaxtextarea-2.6.0-SNAPSHOT.jar
cplus-libparser-0.0.1.jar
jsoup-htmlparser-1.8.1.jar
arduino-autocomplete.jar

**Comment by ashottonoyan** [comment]
Already tried. See comment above for the second picture with the new error.

**Comment by ricardojlrufino** [comment]
You can run the console to see the stack trace ?

**Comment by ashottonoyan** [comment]
Nothing in console

Cheers,
Ashot

**Comment by ashottonoyan** [comment]
any success?

**Comment by ricardojlrufino** [comment]
sorry , I could not get a mac to test !
you would like to help solve ?

**Comment by ashottonoyan** [comment]
Sure. When?

Cheers,
Ashot

**Comment by ricardojlrufino** [comment]
you can try to build from sources, guide:
https://github.com/arduino/Arduino/wiki/Building-Arduino

I think the problem is just the dependencies, or the version of java
but this week I get a Mac to test ...

**Comment by ashottonoyan** [comment]
I did builds on Linux.

Tried this and it did work, but no autocomplete:
`ant clean dist -Dplatform=macosx-java-latest`

Tried this, same error as before:
`ant clean dist -Dplatform=macosx`

![f43e6e1c-cb22-11e4-98af-cb7ba890987a](https://cloud.githubusercontent.com/assets/612529/6834219/9903999a-d343-11e4-952b-9b49b4772566.png)

**Comment by ashottonoyan** [comment]
Sorry, this does work perfect! Also autocomplete.
`ant clean dist -Dplatform=macosx-java-latest`

Autocomplete didn't work when I run from Downloads folder. After moving to Applications, all works great. Thanks!

**Comment by ricardojlrufino** [comment]
It's work using: `ant clean dist -Dplatform=macosx` ?

thank you for your contribution.

**Comment by ashottonoyan** [comment]
No, but this works:
`ant clean dist -Dplatform=macosx-java-latest`

**Comment by duff2013** [comment]
I tried that also but get this error:

```
BUILD FAILED
/Users/duff/Documents/Ardruino Build/Arduino/build/build.xml:85: The following error occurred while executing this line:
/Users/duff/Documents/Ardruino Build/Arduino/build/build.xml:266: java.lang.UnsupportedClassVersionError: com/oracle/appbundler/AppBundlerTask : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at org.apache.tools.ant.AntClassLoader.defineClassFromData(AntClassLoader.java:1136)
    at org.apache.tools.ant.AntClassLoader.getClassFromStream(AntClassLoader.java:1307)
    at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1362)
    at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1323)
    at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1076)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at org.apache.tools.ant.taskdefs.Definer.addDefinition(Definer.java:579)
    at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:237)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
    at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

I should mention this is the first time I built the Arduino IDE so it could be my ant distro is not setup right.

**Comment by ricardojlrufino** [comment]
This problem is java version

**Comment by duff2013** [comment]
Ok thanks, so this release needs the latest java? Did you ever get a mac?
